docker:
  - image: docker.mirror.hashicorp.services/node:12
steps:
  - checkout
  - run:
      name: Push content to Algolia Index
      command: |
        cd website/
        npm install
        node scripts/index_search_content.js