# ***
# WARNING: Do not EDIT or MERGE this file, it is generated by packagespec.
# ***

LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_ID             := 00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_TYPE           := base
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_BASE_LAYER     := 
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_SOURCE_INCLUDE := 
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_SOURCE_EXCLUDE := 
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_CACHE_KEY_FILE := .buildcache/cache-keys/base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa
LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_ARCHIVE_FILE   := .buildcache/archives/00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_ID),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_TYPE),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_BASE_LAYER),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_SOURCE_INCLUDE),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_SOURCE_EXCLUDE),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_CACHE_KEY_FILE),$(LAYER_00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa_ARCHIVE_FILE)))

LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_ID             := 01-ui-d280a4872cd4f689a9fa866f8e618210939659d9
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_TYPE           := ui
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_BASE_LAYER     := 00-base-b2b897ce4eb6896c61cf4806ecc19a11bc7474aa
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_SOURCE_INCLUDE := internal/ui/VERSION
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_SOURCE_EXCLUDE := 
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_CACHE_KEY_FILE := .buildcache/cache-keys/ui-d280a4872cd4f689a9fa866f8e618210939659d9
LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_ARCHIVE_FILE   := .buildcache/archives/01-ui-d280a4872cd4f689a9fa866f8e618210939659d9.tar.gz
$(eval $(call LAYER,$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_ID),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_TYPE),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_BASE_LAYER),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_SOURCE_INCLUDE),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_SOURCE_EXCLUDE),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_CACHE_KEY_FILE),$(LAYER_01-ui-d280a4872cd4f689a9fa866f8e618210939659d9_ARCHIVE_FILE)))

LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_ID             := 02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_TYPE           := go-modules
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_BASE_LAYER     := 01-ui-d280a4872cd4f689a9fa866f8e618210939659d9
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_SOURCE_INCLUDE := go.mod go.sum
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_SOURCE_EXCLUDE := 
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_CACHE_KEY_FILE := .buildcache/cache-keys/go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd
LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_ARCHIVE_FILE   := .buildcache/archives/02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd.tar.gz
$(eval $(call LAYER,$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_ID),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_TYPE),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_BASE_LAYER),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_SOURCE_INCLUDE),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_SOURCE_EXCLUDE),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_CACHE_KEY_FILE),$(LAYER_02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd_ARCHIVE_FILE)))

LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_ID             := 03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_TYPE           := copy-source
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_BASE_LAYER     := 02-go-modules-54d68de5b0e9dce10dab8d519be945ba7758efdd
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_SOURCE_INCLUDE := *.go
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_SOURCE_EXCLUDE := 
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e
LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_ARCHIVE_FILE   := .buildcache/archives/03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e.tar.gz
$(eval $(call LAYER,$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_ID),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_TYPE),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_BASE_LAYER),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_SOURCE_INCLUDE),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_SOURCE_EXCLUDE),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_CACHE_KEY_FILE),$(LAYER_03-copy-source-df70d84b48e1fe48d09efc041bd603cdb8cd0d7e_ARCHIVE_FILE)))
