linters:
  disable-all: true
  enable:
    - staticcheck
    - stylecheck

issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1005:"
    - linters:
        - stylecheck
      text: "ST1003:"
