// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-04-30 11:21:04.8535614 -0400 EDT m=+0.008417801
package hosts

import (
	"encoding/json"
	"time"

	"github.com/fatih/structs"
	"github.com/hashicorp/watchtower/api/internal/strutil"
)

type Host struct {
	defaultFields []string

	// Output only.
	Uri          *string `json:"uri,omitempty"`
	FriendlyName *string `json:"friendly_name,omitempty"`
	// The time this host was created.
	// Output only.
	CreatedTime time.Time `json:"created_time,omitempty"`
	// The time this host was last updated.
	// Output only.
	UpdatedTime time.Time `json:"updated_time,omitempty"`
	// Marks the host as disabled.  Default is false.
	Disabled *bool `json:"disabled,omitempty"`
	// This field is required.
	Address *string `json:"address,omitempty"`
}

func (s *Host) SetDefault(key string) {
	s.defaultFields = strutil.AppendIfMissing(s.defaultFields, key)
}

func (s *Host) UnsetDefault(key string) {
	s.defaultFields = strutil.StrListDelete(s.defaultFields, key)
}

func (s Host) MarshalJSON() ([]byte, error) {
	m := structs.Map(s)
	if m == nil {
		m = make(map[string]interface{})
	}
	for _, k := range s.defaultFields {
		m[k] = nil
	}
	return json.Marshal(m)
}
