// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package sessionrecordings

type Credential struct {
	Id              string                 `json:"id,omitempty"`
	CredentialStore *CredentialStore       `json:"credential_store,omitempty"`
	Name            string                 `json:"name,omitempty"`
	Description     string                 `json:"description,omitempty"`
	Purposes        []string               `json:"purposes,omitempty"`
	Type            string                 `json:"type,omitempty"`
	Attributes      map[string]interface{} `json:"attributes,omitempty"`
}
