// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2026
// SPDX-License-Identifier: MPL-2.0

package sessionrecordings

import (
	"time"

	"github.com/hashicorp/boundary/api"
	"github.com/hashicorp/boundary/api/scopes"
)

type Export struct {
	Id                    string            `json:"id,omitempty"`
	Scope                 *scopes.ScopeInfo `json:"scope,omitempty"`
	MimeType              string            `json:"mime_type,omitempty"`
	State                 string            `json:"state,omitempty"`
	ProgressPercent       uint32            `json:"progress_percent,omitempty"`
	WorkerId              string            `json:"worker_id,omitempty"`
	CreatedTime           time.Time         `json:"created_time,omitempty"`
	UpdatedTime           time.Time         `json:"updated_time,omitempty"`
	Version               uint32            `json:"version,omitempty"`
	ConnectionRecordingId string            `json:"connection_recording_id,omitempty"`
	Error                 string            `json:"error,omitempty"`
	AuthorizedActions     []string          `json:"authorized_actions,omitempty"`
}

type ExportReadResult struct {
	Item     *Export
	Response *api.Response
}

func (n ExportReadResult) GetItem() *Export {
	return n.Item
}

func (n ExportReadResult) GetResponse() *api.Response {
	return n.Response
}

type ExportCreateResult = ExportReadResult

type ExportDeleteResult struct {
	Response *api.Response
}

// GetItem will always be nil for ExportDeleteResult
func (n ExportDeleteResult) GetItem() any {
	return nil
}

func (n ExportDeleteResult) GetResponse() *api.Response {
	return n.Response
}

type ExportListResult struct {
	Items        []*Export `json:"items,omitempty"`
	EstItemCount uint      `json:"est_item_count,omitempty"`
	RemovedIds   []string  `json:"removed_ids,omitempty"`
	ListToken    string    `json:"list_token,omitempty"`
	ResponseType string    `json:"response_type,omitempty"`
	Response     *api.Response

	// The following fields are used for cached information when client-directed
	// pagination is used.
	recursive     bool
	pageSize      uint32
	scopeId       string
	allRemovedIds []string
}

func (n ExportListResult) GetItems() []*Export {
	return n.Items
}

func (n ExportListResult) GetEstItemCount() uint {
	return n.EstItemCount
}

func (n ExportListResult) GetRemovedIds() []string {
	return n.RemovedIds
}

func (n ExportListResult) GetListToken() string {
	return n.ListToken
}

func (n ExportListResult) GetResponseType() string {
	return n.ResponseType
}

func (n ExportListResult) GetResponse() *api.Response {
	return n.Response
}
