// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2026
// SPDX-License-Identifier: MPL-2.0

package sessionrecordings

type RecordingState struct {
	StorageState             string `json:"storage_state,omitempty"`
	SyncingErrorDetails      string `json:"syncing_error_details,omitempty"`
	VerificationErrorDetails string `json:"verification_error_details,omitempty"`
}
