// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package sessionrecordings

type ValuesAtTime struct {
	User                *User                `json:"user,omitempty"`
	Target              *Target              `json:"target,omitempty"`
	Host                *Host                `json:"host,omitempty"`
	Credentials         []*Credential        `json:"credentials,omitempty"`
	CredentialLibraries []*CredentialLibrary `json:"credential_libraries,omitempty"`
}
