// Code generated by "make api"; DO NOT EDIT.
package authmethods

type PasswordAuthMethodAttributes struct {
	MinLoginNameLength uint32 `json:"min_login_name_length,omitempty"`
	MinPasswordLength  uint32 `json:"min_password_length,omitempty"`
}
