// Code generated by "make api"; DO NOT EDIT.
package targets

type CredentialLibrary struct {
	Id                string `json:"id,omitempty"`
	CredentialStoreId string `json:"credential_store_id,omitempty"`
	Purpose           string `json:"purpose,omitempty"`
}
