// Code generated by "make api"; DO NOT EDIT.
package targets

type CredentialLibrary struct {
	Id                string `json:"id,omitempty"`
	Name              string `json:"name,omitempty"`
	Description       string `json:"description,omitempty"`
	CredentialStoreId string `json:"credential_store_id,omitempty"`
	Type              string `json:"type,omitempty"`
}
