// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

package targets

type HostSource struct {
	Id            string `json:"id,omitempty"`
	HostCatalogId string `json:"host_catalog_id,omitempty"`
}
