// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package targets

type SessionCredential struct {
	CredentialSource *CredentialSource      `json:"credential_source,omitempty"`
	Secret           *SessionSecret         `json:"secret,omitempty"`
	Credential       map[string]interface{} `json:"credential,omitempty"`
}
