// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package targets

import (
	"time"

	"github.com/hashicorp/boundary/api/scopes"
)

type SessionAuthorizationData struct {
	SessionId         string            `json:"session_id,omitempty"`
	TargetId          string            `json:"target_id,omitempty"`
	Scope             *scopes.ScopeInfo `json:"scope,omitempty"`
	CreatedTime       time.Time         `json:"created_time,omitempty"`
	Type              string            `json:"type,omitempty"`
	ConnectionLimit   int32             `json:"connection_limit,omitempty"`
	EndpointPort      uint32            `json:"endpoint_port,omitempty"`
	Expiration        time.Time         `json:"expiration,omitempty"`
	Certificate       []byte            `json:"certificate,omitempty"`
	PrivateKey        []byte            `json:"private_key,omitempty"`
	HostId            string            `json:"host_id,omitempty"`
	Endpoint          string            `json:"endpoint,omitempty"`
	WorkerInfo        []*WorkerInfo     `json:"worker_info,omitempty"`
	DefaultClientPort uint32            `json:"default_client_port,omitempty"`
}
