// Code generated by "make api"; DO NOT EDIT.
package scopes

type ScopeInfo struct {
	Id            string `json:"id,omitempty"`
	Type          string `json:"type,omitempty"`
	Name          string `json:"name,omitempty"`
	Description   string `json:"description,omitempty"`
	ParentScopeId string `json:"parent_scope_id,omitempty"`
}
