// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package roles

type GrantJson struct {
	Id      string   `json:"id,omitempty"`
	Type    string   `json:"type,omitempty"`
	Actions []string `json:"actions,omitempty"`
}
