// Code generated by "make api"; DO NOT EDIT.
package roles

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/watchtower/api"
	"github.com/hashicorp/watchtower/api/scopes"
)

type Role struct {
	Id           string            `json:"id,omitempty"`
	Scope        *scopes.ScopeInfo `json:"scope,omitempty"`
	Name         string            `json:"name,omitempty"`
	Description  string            `json:"description,omitempty"`
	CreatedTime  time.Time         `json:"created_time,omitempty"`
	UpdatedTime  time.Time         `json:"updated_time,omitempty"`
	Disabled     bool              `json:"disabled,omitempty"`
	GrantScopeId string            `json:"grant_scope_id,omitempty"`
	Version      uint32            `json:"version,omitempty"`
	PrincipalIds []string          `json:"principal_ids,omitempty"`
	Principals   []*Principal      `json:"principals,omitempty"`
	GrantStrings []string          `json:"grant_strings,omitempty"`
	Grants       []*Grant          `json:"grants,omitempty"`
}

type RoleClient struct {
	client *api.Client
}

func New(c *api.Client) *RoleClient {
	return &RoleClient{client: c}
}

func (c *RoleClient) Read(ctx context.Context, roleId string, opt ...Option) (*Role, *api.Error, error) {
	if roleId == "" {
		return nil, nil, fmt.Errorf("empty roleId value passed into List request")
	}

	if c.client == nil {
		return nil, nil, fmt.Errorf("nil client")
	}

	_, apiOpts := getOpts(opt...)

	req, err := c.client.NewRequest(ctx, "GET", fmt.Sprintf("roles/%s", roleId), nil, apiOpts...)
	if err != nil {
		return nil, nil, fmt.Errorf("error creating Read request: %w", err)
	}

	resp, err := c.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("error performing client request during Read call: %w", err)
	}

	target := new(Role)
	apiErr, err := resp.Decode(target)
	if err != nil {
		return nil, nil, fmt.Errorf("error decoding Read response: %w", err)
	}

	return target, apiErr, nil
}

func (c *RoleClient) List(ctx context.Context, opt ...Option) ([]Role, *api.Error, error) {
	if c.client == nil {
		return nil, nil, fmt.Errorf("nil client")
	}

	_, apiOpts := getOpts(opt...)

	req, err := c.client.NewRequest(ctx, "GET", fmt.Sprintf("roles"), nil, apiOpts...)
	if err != nil {
		return nil, nil, fmt.Errorf("error creating List request: %w", err)
	}

	resp, err := c.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("error performing client request during List call: %w", err)
	}

	type listResponse struct {
		Items []Role
	}
	target := &listResponse{}
	apiErr, err := resp.Decode(target)
	if err != nil {
		return nil, nil, fmt.Errorf("error decoding List response: %w", err)
	}

	return target.Items, apiErr, nil
}

func (c *RoleClient) Create(ctx context.Context, opt ...Option) (*Role, *api.Error, error) {
	if c.client == nil {
		return nil, nil, fmt.Errorf("nil client")
	}

	opts, apiOpts := getOpts(opt...)

	req, err := c.client.NewRequest(ctx, "POST", fmt.Sprintf("roles"), opts.valueMap, apiOpts...)
	if err != nil {
		return nil, nil, fmt.Errorf("error creating Create request: %w", err)
	}

	resp, err := c.client.Do(req)
	if err != nil {
		return nil, nil, fmt.Errorf("error performing client request during Read call: %w", err)
	}

	target := new(Role)
	apiErr, err := resp.Decode(target)
	if err != nil {
		return nil, nil, fmt.Errorf("error decoding Create response: %w", err)
	}

	return target, apiErr, nil
}

func (c *RoleClient) Delete(ctx context.Context, roleId string, opt ...Option) (bool, *api.Error, error) {
	if roleId == "" {
		return false, nil, fmt.Errorf("empty roleId value passed into List request")
	}

	if c.client == nil {
		return false, nil, fmt.Errorf("nil client")
	}

	_, apiOpts := getOpts(opt...)

	req, err := c.client.NewRequest(ctx, "DELETE", fmt.Sprintf("roles/%s", roleId), nil, apiOpts...)
	if err != nil {
		return false, nil, fmt.Errorf("error creating Delete request: %w", err)
	}

	resp, err := c.client.Do(req)
	if err != nil {
		return false, nil, fmt.Errorf("error performing client request during Delete call: %w", err)
	}

	type deleteResponse struct {
		Existed bool
	}
	target := &deleteResponse{}
	apiErr, err := resp.Decode(target)
	if err != nil {
		return false, nil, fmt.Errorf("error decoding Delete response: %w", err)
	}

	return target.Existed, apiErr, nil
}

type Option func(*options)

type options struct {
	valueMap    map[string]interface{}
	withScopeId string
}

func getDefaultOptions() options {
	return options{
		valueMap: make(map[string]interface{}),
	}
}

func getOpts(opt ...Option) (options, []api.Option) {
	opts := getDefaultOptions()
	for _, o := range opt {
		o(&opts)
	}
	var apiOpts []api.Option
	if opts.withScopeId != "" {
		apiOpts = append(apiOpts, api.WithScopeId(opts.withScopeId))
	}
	return opts, apiOpts
}

func DefaultScopeId() Option {
	return func(o *options) {
		o.withScopeId = ""
	}
}

func WithScopeId(id string) Option {
	return func(o *options) {
		o.withScopeId = id
	}
}

func WithName(inName string) Option {
	return func(o *options) {
		o.valueMap["name"] = inName
	}
}

func DefaultName() Option {
	return func(o *options) {
		o.valueMap["name"] = nil
	}
}

func WithDescription(inDescription string) Option {
	return func(o *options) {
		o.valueMap["description"] = inDescription
	}
}

func DefaultDescription() Option {
	return func(o *options) {
		o.valueMap["description"] = nil
	}
}

func WithDisabled(inDisabled bool) Option {
	return func(o *options) {
		o.valueMap["disabled"] = inDisabled
	}
}

func DefaultDisabled() Option {
	return func(o *options) {
		o.valueMap["disabled"] = nil
	}
}

func WithGrantScopeId(inGrantScopeId string) Option {
	return func(o *options) {
		o.valueMap["grant_scope_id"] = inGrantScopeId
	}
}

func DefaultGrantScopeId() Option {
	return func(o *options) {
		o.valueMap["grant_scope_id"] = nil
	}
}

func WithVersion(inVersion uint32) Option {
	return func(o *options) {
		o.valueMap["version"] = inVersion
	}
}

func DefaultVersion() Option {
	return func(o *options) {
		o.valueMap["version"] = nil
	}
}

func WithPrincipalIds(inPrincipalIds []string) Option {
	return func(o *options) {
		o.valueMap["principal_ids"] = inPrincipalIds
	}
}

func DefaultPrincipalIds() Option {
	return func(o *options) {
		o.valueMap["principal_ids"] = nil
	}
}

func WithPrincipals(inPrincipals []*Principal) Option {
	return func(o *options) {
		o.valueMap["principals"] = inPrincipals
	}
}

func DefaultPrincipals() Option {
	return func(o *options) {
		o.valueMap["principals"] = nil
	}
}

func WithGrantStrings(inGrantStrings []string) Option {
	return func(o *options) {
		o.valueMap["grant_strings"] = inGrantStrings
	}
}

func DefaultGrantStrings() Option {
	return func(o *options) {
		o.valueMap["grant_strings"] = nil
	}
}
