Version = '0.1.4'
PortMappings = Hash[
  "api"         => 9200,
  "proxy"       => 9202,
  "linux/api"   => 9300,
  "linux/proxy" => 9302, 
]

Vagrant.configure("2") do |config|
  config.vm.define :linux do |test|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "public_network"
    config.vm.network "forwarded_port", guest: PortMappings['api'], host: PortMappings['linux/api']
    config.vm.network "forwarded_port", guest: PortMappings['proxy'], host: PortMappings['linux/proxy']
    config.vm.synced_folder "tests/", "/tests"
    config.vm.synced_folder "provision/", "/provision"
    config.vm.provision "shell" do |s|
      s.inline = "/provision/boundary-linux.sh" 
      s.args = "#{Version}"
    end 
    config.vm.provision "shell", inline: "/provision/test-linux.sh" 
  end
 end
