#!/usr/bin/env bash

if [[ -z "${CIRCLE_REPOSITORY_URL}" ]]; then
    exit 0
fi

if [[ "${CIRCLE_REPOSITORY_URL}" == *"boundary-enterprise"* ]]; then
  exit 0
fi

if [[ -z ${CIRCLE_CI_ENT_TOK} ]]; then
  exit 0
fi

curl -u ${CIRCLE_CI_ENT_TOK}: \
  -d 'build_parameters[CIRCLE_JOB]=merge-oss-main' \
  https://circleci.com/api/v1.1/project/github/hashicorp/boundary-enterprise/tree/main
