// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package workers

import (
	"time"
)

type Certificate struct {
	Id              string    `json:"id,omitempty"`
	PublicKeySha256 string    `json:"public_key_sha256,omitempty"`
	NotBeforeTime   time.Time `json:"not_before_time,omitempty"`
	NotAfterTime    time.Time `json:"not_after_time,omitempty"`
}
