// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package workers

import (
	"github.com/hashicorp/boundary/api"
)

type CertificateAuthority struct {
	Certs []*Certificate `json:"certs,omitempty"`
}

type CertificateAuthorityReadResult struct {
	Item     *CertificateAuthority
	Response *api.Response
}

func (n CertificateAuthorityReadResult) GetItem() *CertificateAuthority {
	return n.Item
}

func (n CertificateAuthorityReadResult) GetResponse() *api.Response {
	return n.Response
}
