// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package workers

type RemoteStorageState struct {
	Status      string                    `json:"status,omitempty"`
	Permissions *RemoteStoragePermissions `json:"permissions,omitempty"`
}
