// Code generated by "make api"; DO NOT EDIT.
package credentials

type UserPasswordAttributes struct {
	Username     string `json:"username,omitempty"`
	Password     string `json:"password,omitempty"`
	PasswordHmac string `json:"password_hmac,omitempty"`
}
