// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package scopes

import (
	"time"
)

type KeyVersion struct {
	Id          string    `json:"id,omitempty"`
	Version     uint32    `json:"version,omitempty"`
	CreatedTime time.Time `json:"created_time,omitempty"`
}
