// Code generated by "make api"; DO NOT EDIT.
package scopes

import "bytes"

type ScopeInfo struct {
	Id            string `json:"id,omitempty"`
	Type          string `json:"type,omitempty"`
	Name          string `json:"name,omitempty"`
	Description   string `json:"description,omitempty"`
	ParentScopeId string `json:"parent_scope_id,omitempty"`

	lastResponseBody *bytes.Buffer
	lastResponseMap  map[string]interface{}
}

func (n ScopeInfo) LastResponseBody() *bytes.Buffer {
	return n.lastResponseBody
}

func (n ScopeInfo) LastResponseMap() map[string]interface{} {
	return n.lastResponseMap
}
