// Code generated by "make api"; DO NOT EDIT.
package api

import "bytes"

type Error struct {
	Kind    string        `json:"kind,omitempty"`
	ErrorId string        `json:"error_id,omitempty"`
	Message string        `json:"message,omitempty"`
	Details *ErrorDetails `json:"details,omitempty"`

	response *Response
}

func (n Error) ResponseBody() *bytes.Buffer {
	return n.response.Body
}

func (n Error) ResponseMap() map[string]interface{} {
	return n.response.Map
}

func (n Error) ResponseStatus() int {
	return n.response.HttpResponse().StatusCode
}

func (n Error) ResponseTraceId() string {
	return n.response.HttpResponse().Header.Get("TraceId")
}
