// Code generated by "make api"; DO NOT EDIT.
// Copyright IBM Corp. 2020, 2025
// SPDX-License-Identifier: MPL-2.0

package api

type FieldError struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
