// Code generated by "make api"; DO NOT EDIT.
package api

import "bytes"

type FieldError struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`

	lastResponseBody *bytes.Buffer
	lastResponseMap  map[string]interface{}
}

func (n FieldError) LastResponseBody() *bytes.Buffer {
	return n.lastResponseBody
}

func (n FieldError) LastResponseMap() map[string]interface{} {
	return n.lastResponseMap
}

type FieldErrorListResult struct {
	Items            []*FieldError
	lastResponseBody *bytes.Buffer
	lastResponseMap  map[string]interface{}
}

func (n FieldErrorListResult) LastResponseBody() *bytes.Buffer {
	return n.lastResponseBody
}

func (n FieldErrorListResult) LastResponseMap() map[string]interface{} {
	return n.lastResponseMap
}

type FieldErrorDeleteResult struct {
	Existed          bool
	lastResponseBody *bytes.Buffer
	lastResponseMap  map[string]interface{}
}

func (n FieldErrorDeleteResult) LastResponseBody() *bytes.Buffer {
	return n.lastResponseBody
}

func (n FieldErrorDeleteResult) LastResponseMap() map[string]interface{} {
	return n.lastResponseMap
}
