// Code generated by "make api"; DO NOT EDIT.
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package api

type WarningResponse struct {
	Warnings []*Warning `json:"warnings,omitempty"`
}
