---
name: enos-aws-configure-creds-static

on:
  workflow_call:

jobs:
  configure-aws-credentials:
    name: Configure AWS Credentials
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CI }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::271311691044:user/github_actions-boundary_ci
          role-skip-session-tagging: true
          role-duration-seconds: 3600
