name: "Pull Request Labeler"
on:
- pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    steps:
    - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4  # TSCCR: could not find tsccr entry for actions/labeler
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
