name: "golangci-lint"

on:
  pull_request:
    paths-ignore:
      - 'website/**'

permissions:
  contents: read

jobs:
  lint:
    name: "Run Linter"
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ steps.get-go-version.outputs.go-version }}"
          cache: false
      - name: Determine Go cache paths
        id: go-cache-paths
        run: |
          echo "go-mod=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - name: Set up Go modules cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5.0.3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod
      - name: Install Dependencies
        # if we really need to we can update this to run `make tools`
        # later but its just not necessary to only run linters
        run: |
          make golangci-lint
      - name: Running Linters
        run: |
          LINT_DIFF_BRANCH="origin/${GITHUB_BASE_REF}" make lint-diff
