name: trigger-test-cron

# This workflow will run every two hours to determine the frequency of test failures
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger test workflow
        run: |
          run=10
          for i in $(seq $run); do
            gh workflow run test.yml
          done
        env:
          GITHUB_TOKEN: ${{ github.token }}
