// Code generated by "make api"; DO NOT EDIT.
package groups

import (
	"encoding/json"
	"strings"
	"time"

	"github.com/fatih/structs"

	"github.com/hashicorp/watchtower/api"
	"github.com/hashicorp/watchtower/api/internal/strutil"
)

type Group struct {
	Client *api.Client `json:"-"`

	defaultFields []string

	// The ID of the Project
	// Output only.
	Id string `json:"id,omitempty"`
	// Optional name for identification purposes
	Name *string `json:"name,omitempty"`
	// Optional user-set descripton for identification purposes
	Description *string `json:"description,omitempty"`
	// The time this resource was created
	// Output only.
	CreatedTime time.Time `json:"created_time,omitempty"`
	// The time this resource was last updated.
	// Output only.
	UpdatedTime time.Time `json:"updated_time,omitempty"`
	// Whether the resource is disabled
	Disabled *bool `json:"disabled,omitempty"`
	// The version can be used in subsiquent write requests to ensure this resource
	// has not changed and to fail the write if it has.
	// Output only.
	Version uint32 `json:"version,omitempty"`
	// Contains the list of member ids in this group.
	// Output only.
	MemberIds []string `json:"member_ids,omitempty"`
	// The members of this group.
	// Output only.
	Members []*Member `json:"members,omitempty"`
}

func (s *Group) SetDefault(key string) {
	lowerKey := strings.ToLower(key)
	validMap := map[string]string{"createdtime": "created_time", "description": "description", "disabled": "disabled", "id": "id", "memberids": "member_ids", "members": "members", "name": "name", "updatedtime": "updated_time", "version": "version"}
	for k, v := range validMap {
		if k == lowerKey || v == lowerKey {
			s.defaultFields = strutil.AppendIfMissing(s.defaultFields, v)
			return
		}
	}
}

func (s *Group) UnsetDefault(key string) {
	lowerKey := strings.ToLower(key)
	validMap := map[string]string{"createdtime": "created_time", "description": "description", "disabled": "disabled", "id": "id", "memberids": "member_ids", "members": "members", "name": "name", "updatedtime": "updated_time", "version": "version"}
	for k, v := range validMap {
		if k == lowerKey || v == lowerKey {
			s.defaultFields = strutil.StrListDelete(s.defaultFields, v)
			return
		}
	}
}

func (s Group) MarshalJSON() ([]byte, error) {
	m := structs.Map(s)
	if m == nil {
		m = make(map[string]interface{})
	}
	for _, k := range s.defaultFields {
		m[k] = nil
	}
	return json.Marshal(m)
}
